create table tb_customer (
  id bigint not null generated by default as identity
  (start with 1 increment by 1),
  name varchar(60) not null,
  version bigint not null,
  created_at timestamp WITH TIME ZONE,
  updated_at timestamp WITH TIME ZONE,

  primary key (id)
);
