create table tb_product (
  id bigint not null generated by default as identity
  (start with 1 increment by 1),
  name varchar(60) not null,
  value decimal(5,2) not null,
  category_id bigint not null,
  version bigint not null,
  created_at timestamp WITH TIME ZONE,
  updated_at timestamp WITH TIME ZONE,

   primary key (id),

   constraint fk_product_category foreign key (categoty_id) references tb_product(id)
);
